#!/bin/sh
#
# Copyright (c) 2025 Stefanos Stefanidis. All rights reserved.
#

#
# Use C locale for the date command, regardless of the user's locale.
# This way, the date will be in English and not in the user's language,
# if it doesn't happen to be English.
#
LC_TIME=C

t=$(date +'%Y/%m/%d %H:%M:%S')
d=$(date +'%h %e, %Y')
revd=$(date +'%Y/%m/%d')
ti=$(date)
d2=$(date +'%y%m%d-%H%M')

mach=$1

mj=1
mi=0

rmj=1
rmi=$(git rev-list HEAD --count)

commit=$(git rev-parse --short HEAD)
br=$(git rev-parse --abbrev-ref HEAD)

cat > $2 << EOF
/*
 * DO NOT EDIT THIS FILE!
 * IT IS GENERATED AUTOMATICALLY BY THE newvers.sh SCRIPT.
 */

#include <efi.h>
#include <efilib.h>

#if __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
static const CHAR16 version[] = L"HeliumBoot Version ${mj}.${mi} ${mach}   ${d} (BE)";
#elif __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
static const CHAR16 version[] = L"HeliumBoot Version ${mj}.${mi} ${mach}   ${d} (LE)";
#endif

static const CHAR16 revision[] = L"${rmj}.${rmi}";
static const CHAR16 blddate[] = L"${ti}";
static const CHAR16 revdate[] = L"${revd}";
static const CHAR16 commitno[] = L"${commit}";
static const CHAR16 buildno[] = L"${mj}.${mi}.${rmi}.${br}.${d2}";

const CHAR16 *
getversion(void)
{
	return version;
}

const CHAR16 *
getrevision(void)
{
	return revision;
}

const CHAR16 *
getblddate(void)
{
	return blddate;
}

const CHAR16 *
getrevdate(void)
{
	return revdate;
}

const CHAR16 *
getcommitno(void)
{
	return commitno;
}

const CHAR16 *
getbuildno(void)
{
	return buildno;
}

EOF
