#!/bin/sh
#
# HeliumBoot/EFI - A simple UEFI bootloader.
#
# Copyright (c) 2025 Stefanos Stefanidis.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software
# without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# Use C locale for the date command, regardless of the user's locale.
# This way, the date will be in English and not in the user's language,
# if it doesn't happen to be English.
#
LC_TIME=C

t=$(date +'%Y/%m/%d %H:%M:%S')
d=$(date +'%h %e, %Y')
revd=$(date +'%Y/%m/%d')
ti=$(date)
d2=$(date +'%y%m%d-%H%M')

mach=$1

mj=1
mi=0

rmj=1
rmi=$(git rev-list HEAD --count)

commit=$(git rev-parse --short HEAD)
br=$(git rev-parse --abbrev-ref HEAD)

cat > $2 << EOF
/*
 * DO NOT EDIT THIS FILE!
 * IT IS GENERATED AUTOMATICALLY BY THE newvers.sh SCRIPT. EDIT THAT INSTEAD.
 */

#include <efi.h>
#include <efilib.h>

#if defined(DEBUG_BLD) && !defined(DEV_BLD)
static const CHAR16 version[] = L"Kyasarin ${rmj}.${rmi} ${mach} (Debug)   ${t}";
#elif !defined(DEBUG_BLD) && defined(DEV_BLD)
static const CHAR16 version[] = L"Kyasarin ${rmj}.${rmi} ${mach} (Dev)   ${t}";
#elif defined(DEBUG_BLD) && defined(DEV_BLD)
static const CHAR16 version[] = L"Kyasarin ${rmj}.${rmi} ${mach} (Dev/Debug)   ${t}";
#else
static const CHAR16 version[] = L"HeliumBoot Version ${mj}.${mi} ${mach}   ${d}";
#endif

static const CHAR16 revision[] = L"${rmj}.${rmi}";
static const CHAR16 blddate[] = L"${ti}";
static const CHAR16 revdate[] = L"${revd}";
static const CHAR16 commitno[] = L"${commit}";
static const CHAR16 buildno[] = L"${mj}.${mi}.${rmi}.${br}.${d2}";

const CHAR16 *
getversion(void)
{
	return version;
}

const CHAR16 *
getrevision(void)
{
	return revision;
}

const CHAR16 *
getblddate(void)
{
	return blddate;
}

const CHAR16 *
getrevdate(void)
{
	return revdate;
}

const CHAR16 *
getcommitno(void)
{
	return commitno;
}

const CHAR16 *
getbuildno(void)
{
	return buildno;
}

EOF
